logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    org.springframework.data.mongodb: ERROR
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    com.ptc.loyalty.reward: DEBUG
    
mongock:
  enabled: false
