version: '3.9'
services:
  redis:
    image: redis:6.2.5
    ports:
      - "6379:6379"
    volumes:
      - //d/data/redis:/var/lib/redis
  mongo:
    image: mongo:4.4.4
    ports:
      - "27017:27017"
    volumes:
      - //d/data/db:/data/db
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper